/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.contacteditor;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Turbiani
 */
public class ContactEditorUI extends javax.swing.JFrame {

    /**
     * Creates new form ContactEditorUI
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botoesMaterias;
    private javax.swing.JButton botaoCalcular;
    private javax.swing.JLabel labelTituloTrabalho;
    private javax.swing.JLabel labelEscolhas;
    private javax.swing.JLabel labelPrimeiraVariavel;
    private javax.swing.JLabel labelSegundaVariavel;
    private javax.swing.JLabel labelTerceiraVariavel;
    private ArrayList<JLabel> labelListVariaveis;
    private javax.swing.JRadioButton materia1;
    private javax.swing.JRadioButton materia2;
    private javax.swing.JRadioButton materia3;
    private javax.swing.JRadioButton materia4;
    private javax.swing.JScrollPane janela;
    private javax.swing.JTextArea textAreaExplicacao;
    private javax.swing.JTextField textFieldPrimeiraVariavel;
    private javax.swing.JTextField textFieldResultado;
    private javax.swing.JTextField textFieldSegundaVariavel;
    private javax.swing.JTextField textFieldTerceiraVariavel;
    private ArrayList<JTextField> textListVariaveis;
    // End of variables declaration//GEN-END:variables

    public ContactEditorUI() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        botoesMaterias = new javax.swing.ButtonGroup();
        labelTituloTrabalho = new javax.swing.JLabel();
        labelEscolhas = new javax.swing.JLabel();
        materia1 = new javax.swing.JRadioButton();
        materia2 = new javax.swing.JRadioButton();
        materia3 = new javax.swing.JRadioButton();
        materia4 = new javax.swing.JRadioButton();
        textFieldPrimeiraVariavel = new javax.swing.JTextField();
        textFieldSegundaVariavel = new javax.swing.JTextField();
        textFieldTerceiraVariavel = new javax.swing.JTextField();
        textFieldResultado = new javax.swing.JTextField();
        botaoCalcular = new javax.swing.JButton();
        janela = new javax.swing.JScrollPane();
        textAreaExplicacao = new javax.swing.JTextArea();
        labelPrimeiraVariavel = new javax.swing.JLabel();
        labelSegundaVariavel = new javax.swing.JLabel();
        labelTerceiraVariavel = new javax.swing.JLabel();
        labelListVariaveis = new ArrayList<>();
        labelListVariaveis.add(labelPrimeiraVariavel);
        labelListVariaveis.add(labelSegundaVariavel);
        labelListVariaveis.add(labelTerceiraVariavel);
        textListVariaveis = new ArrayList<>();
        textListVariaveis.add(textFieldPrimeiraVariavel);
        textListVariaveis.add(textFieldSegundaVariavel);
        textListVariaveis.add(textFieldTerceiraVariavel);

        setBaseText();
        addPhysicsAreas();
        textFieldPrimeiraVariavel.addActionListener(evt -> jTextField1ActionPerformed(evt));

        botaoCalcular.setText("Calcular");
        botaoCalcular.addActionListener(evt -> botaoCalcularActionPerformed(evt));

        textFieldSegundaVariavel.addActionListener(evt -> jTextField3ActionPerformed(evt));

        textAreaExplicacao.setColumns(20);
        textAreaExplicacao.setRows(5);
        janela.setViewportView(textAreaExplicacao);


        textFieldTerceiraVariavel.addActionListener(evt -> jTextField4ActionPerformed(evt));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelTituloTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addComponent(materia1)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(materia3)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(materia2))
                                                        .addComponent(labelEscolhas, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(18, 18, 18)
                                                .addComponent(materia4))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(janela, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(textFieldResultado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                        .addComponent(labelPrimeiraVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(labelSegundaVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(labelTerceiraVariavel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(textFieldPrimeiraVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(textFieldSegundaVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(textFieldTerceiraVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGap(245, 245, 245)))
                                        .addComponent(botaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelTituloTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelEscolhas)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(materia1)
                                        .addComponent(materia3)
                                        .addComponent(materia2)
                                        .addComponent(materia4))
                                .addGap(4, 4, 4)
                                .addComponent(janela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelTerceiraVariavel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(labelPrimeiraVariavel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(labelSegundaVariavel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textFieldPrimeiraVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldSegundaVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldTerceiraVariavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(botaoCalcular)
                                .addGap(18, 18, 18)
                                .addComponent(textFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPhysicsAreas(){
        botoesMaterias.add(materia1);
        materia1.setText("Cinemática");
        materia1.addActionListener(evt -> materia1ActionPerformed(evt));

        botoesMaterias.add(materia2);
        materia2.setText("Mola");
        materia2.addActionListener(evt -> materia2ActionPerformed(evt));

        botoesMaterias.add(materia3);
        materia3.setText("Onda");
        materia3.addActionListener(evt -> materia3ActionPerformed(evt));

        botoesMaterias.add(materia4);
        materia4.setText("Eletricidade");
        materia4.addActionListener(evt -> materia4ActionPerformed(evt));
    }

    private void setBaseText(){
        labelTituloTrabalho.setText("Projeto Integrador 5 - Grupo 4N59");
        labelEscolhas.setText("Escolha as opções de simulação:");
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void materia4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        labelPrimeiraVariavel.setText("Aqui abre a simulação de Eletricidade");
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void materia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        textAreaExplicacao.setText("Esta simulação calcula a Velocidade da onda com os dados do comprimento de onda\ne da frequêcia de onda \n\nA equação utilizada é V = y * f\nNa caixa abaixo insira o valor do comprimento de onda e frequência: ");
        List<String> listaVariaveis = new ArrayList<>();
        listaVariaveis.add("y");
        listaVariaveis.add("f");
        setVariables(listaVariaveis);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void materia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        labelPrimeiraVariavel.setText("Aqui abre a simulação de Mola");
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void materia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:

        textAreaExplicacao.setText("Esta simulação calcula a Velocidade Final com os dados da Velocidade Inicial, \nAceleração e o Tempo observado pela equação Vf = Vi + (a*t). \n\nNa caixa abaixo insira o valor da Velocidade Inicial, Aceleração e Tempo: ");
        List<String> listaVariaveis = new ArrayList<>();
        listaVariaveis.add("Vi");
        listaVariaveis.add("a");
        listaVariaveis.add("t");
        setVariables(listaVariaveis);

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void botaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if(materia1.isSelected()){

            String textAstring = textFieldPrimeiraVariavel.getText();
            int textA = Integer.parseInt(textAstring);
            String textBstring = textFieldSegundaVariavel.getText();
            int textB = Integer.parseInt(textBstring);
            String textCstring = textFieldTerceiraVariavel.getText();
            int textC = Integer.parseInt(textCstring);

            int v = textA+(textB*textC);
            textFieldResultado.setText(Integer.toString(v));
        }
        if(materia3.isSelected()){

            String textAstring = textFieldPrimeiraVariavel.getText();
            int textA = Integer.parseInt(textAstring);
            String textBstring = textFieldSegundaVariavel.getText();
            int textB = Integer.parseInt(textBstring);

            int vo = textA*textB;
            textFieldResultado.setText(Integer.toString(vo));
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void setVariables(List<String> listaVariaveis){
        int index = 0;
        for (JTextField textField:textListVariaveis) {
            if(index < listaVariaveis.size()){
                textField.setEnabled(true);
                if(labelListVariaveis.size() >= index)
                    labelListVariaveis.get(index).setText(listaVariaveis.get(index));
            }
            else {
                textField.setEnabled(false);
                if(labelListVariaveis.size() >= index)
                    labelListVariaveis.get(index).setText("");
            }
            index++;
        }
    }
}